### ISSUE TITLE
Prototype Database TODO

### ISSUE THREAD

**Issue by GregoryConrad** [CS3733-D20-Team-O/CS3733-D20-Team-O-Iteration#5]
- [x] Add Guice to dependencies
- [x] Rework IDatabaseWrapper into ```@Data public abstract class DatabaseWrapperBase``` with a ```private final Connection``` that has ```@RequiredArgsConstructor``` with ```@Inject```
- [x] Create a ```Connection``` enum Singleton
- [x] Setup CSVHandlerBase with ```@Inject```
